
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mywebapi
  namespace: ${GITHUB_PR_SOURCE_BRANCH}
  labels:
    app: mywebapi
spec:
  rules:
    - host: example.local
      http:
        paths:
          - path: /
            backend:
              serviceName: mywebapi
              servicePort: http
